config/routes.rb
Ashowofhands::Application.routes.draw do
  get 'log_in' => 'user_sessions#new', as: 'log_in'
  get 'log_out' => 'user_sessions#destroy', as: 'log_out'

  resources :pages
  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authem::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Authem::ControllerSupport
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def new
  end

  def edit
  end

  def show
  end

  def index
  end
end

app/controllers/user_sessions.rb
class UserSession < ApplicationController
  expose(:user) { User.find_by_email(params[:email]) }

  def create
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_back_or_to(:root)
    else
      flash.now.alert = "Your email and password do not match."
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to(:root)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  expose(:user) { User.find_by_email(params[:email]) }

  def create
    if user && user.authenticate(params[:password])
      sign_in(user)
      flash[:notice] = "Logged in successfully!"
      redirect_back_or_to(:root)
    else
      flash.now.alert = "Your email and password do not match."
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to(:root)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user)
  expose(:created_user) { User.new(user_params) }

  def create
    if created_user.save
      redirect_to :root, notice: "Account successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title A Show of Hands
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
%body
  - flash.keys.each do |type|
    %p
      = flash[type]

  = yield

app/views/pages/edit.html.haml
%h1 Pages#edit
%p Find me in app/views/pages/edit.html.haml

app/views/pages/index.html.haml
%h1 A Show Of Hands
- if current_user
  = link_to "Log Out", log_out_path
- else
  = link_to "Log In", log_in_path
  = link_to "Sign Up", new_user_path

app/views/pages/new.html.haml
%h1 Pages#new
%p Find me in app/views/pages/new.html.haml

app/views/pages/show.html.haml
%h1 Pages#show
%p Find me in app/views/pages/show.html.haml

app/views/user_sessions/new.html.haml
%h1 Log In

%fieldset
  = form_tag user_sessions_path do
    .field
      = label_tag :email, "E-Mail"
      %br
      = email_field_tag :email, params[:email]

    .field
      = label_tag :password, "Password"
      %br
      = password_field_tag :password, params[:password]

    .action
      = submit_tag "Log In"

app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.haml

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

app/views/users/new.html.haml
%h1 New User

= form_for user do |f|
  = f.label :email
  = f.email_field :email
  %br
  = f.label :password
  = f.password_field :password
  %br
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  %br
  = f.submit "Sign Up"

app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.haml